### ISSUE TITLE
Deepinsert issue

### ISSUE THREAD

**Issue by zpaulovics** [Soontao/odata-v4-server#82]
Have an issue when trying to deep insert to a one:many  relation from the one side. From the other side works well.

POST http:localhost/v4/Providers

```
{
  "id": "996c132c-6a58-484f-a993-4b47273b172a",
  "name": "ELMŰ-ÉMÁSZ Energiaszolgáltató Zrt.",
  "tax_numver": "12345678-2-44",
  "proposals": [
    {
      "id": "629e492c-9056-46f5-8df4-24c80d6b5dac",
      "name": "Kisfeszültségű ajánlat",
      "voltage_level": "medium-high",
      "consumer_profile": "blank",
      "energy_fee": 34.22,
      "funds": true,
      "nogaranty": false,
      "garanty": true,
      "green": true,
      "loyalty": false,
      "online": true,
      "yearly": false,
      "co2": true,
      "start_date": "2020-09-22",
      "end_date": "2020-09-30",
      "isPublic": true,
      "providerId": "996c132c-6a58-484f-a993-4b47273b172a"
     }
  ]
}
```

```
query: START TRANSACTION
query: INSERT INTO `provider`(`id`, `name`, `tax_number`) VALUES (?, ?, DEFAULT) -- PARAMETERS: ["996c132c-6a58-484f-a993-4b47273b172a","ELMŰ-ÉMÁSZ Energiaszolgáltató Zrt."]
query failed: INSERT INTO `provider`(`id`, `name`, `tax_number`) VALUES (?, ?, DEFAULT) -- PARAMETERS: ["996c132c-6a58-484f-a993-4b47273b172a","ELMŰ-ÉMÁSZ Energiaszolgáltató Zrt."]
error: { Error: ER_NO_DEFAULT_FOR_FIELD: Field 'tax_number' doesn't have a default value
    at Query.Sequence._packetToError (/Users/zpaulovics/gitroot/mekh/pct-app/odatasrv/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/zpaulovics/gitroot/mekh/pct-app/odatasrv/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/zpaulovics/gitroot/mekh/pct-app/odatasrv/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/zpaulovics/gitroot/mekh/pct-app/odatasrv/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/zpaulovics/gitroot/mekh/pct-app/odatasrv/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/zpaulovics/gitroot/mekh/pct-app/odatasrv/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/zpaulovics/gitroot/mekh/pct-app/odatasrv/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/zpaulovics/gitroot/mekh/pct-app/odatasrv/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    --------------------
    at Protocol._enqueue (/Users/zpaulovics/gitroot/mekh/pct-app/odatasrv/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at PoolConnection.query (/Users/zpaulovics/gitroot/mekh/pct-app/odatasrv/node_modules/mysql/lib/Connection.js:198:25)
    at MysqlQueryRunner.<anonymous> (/Users/zpaulovics/gitroot/mekh/pct-app/odatasrv/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:161:44)
    at step (/Users/zpaulovics/gitroot/mekh/pct-app/odatasrv/node_modules/typeorm/node_modules/tslib/tslib.js:141:27)
    at Object.next (/Users/zpaulovics/gitroot/mekh/pct-app/odatasrv/node_modules/typeorm/node_modules/tslib/tslib.js:122:57)
    at fulfilled (/Users/zpaulovics/gitroot/mekh/pct-app/odatasrv/node_modules/typeorm/node_modules/tslib/tslib.js:112:62)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 'ER_NO_DEFAULT_FOR_FIELD',
  errno: 1364,
  sqlMessage: 'Field \'tax_number\' doesn\'t have a default value',
  sqlState: 'HY000',
  index: 0,
  sql:
   'INSERT INTO `provider`(`id`, `name`, `tax_number`) VALUES (\'996c132c-6a58-484f-a993-4b47273b172a\', \'ELMŰ-ÉMÁSZ Energiaszolgáltató Zrt.\', DEFAULT)' }
query: ROLLBACK
```

**Comment by Soontao** [comment]
hi @zpaulovics 

a quick response: 

I find that the top level `tax_number` is misspelling to `tax_numver`, I'm not sure the SQL error is caused by that or not. (because there is no validation on Rest Service payload now, #68)
I will check that tomorrow.

Thanks :)

**Comment by zpaulovics** [comment]
Hi,

I also find out the misspelling, corrected it before, then generated a very new database. The bug is comming from the new setup.

The enties now have got the following structures:

```
import {
    BaseODataModel, Edm, ODataColumn, ODataModel,
    ODataNavigation, withEntitySetName, odata,
    ODataAction, TransactionContext, EdmType
} from '@odata/server';
import { Provider } from './Provider';

// indicate the entity set name for entity
@withEntitySetName('Proposals')
@ODataModel()
export class Proposal extends BaseODataModel {

    @Edm.Guid
    @ODataColumn({ primary: true, generated: "uuid" })
    id: string;

    @Edm.Unicode
    @ODataColumn({ charset: "Utf8", length: 72 })
    name: string;

    @ODataColumn({ type: "enum", enum: ["high", "medium-high", "medium", "medium-low", "low"] })
    voltage_level: string;

    @ODataColumn({ type: "enum", enum: ["blank", "profiles", "controlled", "time-series"] })
    consumer_profile: string;

    @ODataColumn({ type: "decimal", precision: 12, scale: 2  })
    energy_fee: string;

    @ODataColumn({type : "boolean", default: false })
    funds: boolean;

    @ODataColumn({type : "boolean", default: false})
    nogaranty: boolean;

    @ODataColumn({type : "boolean", default: false})
    garanty: boolean;

    @ODataColumn({type : "boolean", default: false})
    discounts: boolean;

    @ODataColumn({type : "boolean", default: false})
    green: boolean;

    @ODataColumn({type : "boolean", default: false})
    domastic: boolean;

    @ODataColumn({type : "boolean", default: false})
    loyalty: boolean;

    @ODataColumn({type : "boolean", default: false})
    online: boolean;

    @ODataColumn({type : "boolean", default: false})
    yearly: boolean;

    @ODataColumn({type : "boolean", default: false})
    co2: boolean;

    @Edm.Date
    @ODataColumn({ type: "date" })
    start_date: string;

    @Edm.Date
    @ODataColumn({ type: "date", nullable: true })
    end_date: string;

    @ODataColumn({type : "boolean", default: true })
    isPublic: boolean;

    @Edm.Guid
    @ODataColumn({ nullable: true, generated: "uuid" })
    providerId: string;

    @ODataNavigation({ type: 'ManyToOne', entity: () => Provider, foreignKey: 'providerId' })
    provider: Provider;

}
```
and

```
import { BaseODataModel, Edm, ODataColumn, ODataModel, ODataNavigation,
    UUIDKeyProperty, withEntitySetName} from '@odata/server';
import { Proposal } from './Proposal';

// indicate the entity set name for entity
@withEntitySetName('Providers')
@ODataModel()
export class Provider extends BaseODataModel {

    @Edm.Guid
    @ODataColumn({ primary: true, generated: "uuid" })
    id: string;

    @Edm.Unicode
    @ODataColumn({ charset: "Utf8", length: 72 })
    name: string;

    @ODataColumn({ length: 13 })
    tax_number: string;

    @ODataNavigation({ type: 'OneToMany', entity: () => Proposal, targetForeignKey: 'providerId' })
    proposals: Proposal[];
}
```
Tanks

**Comment by Soontao** [comment]
@zpaulovics 

I mean the HTTP body payloed is not mapping the entity property name, try this payload: 

```json
{
  "name": "ELMŰ-ÉMÁSZ Energiaszolgáltató Zrt.",
  "tax_number": "12345678-2-44",
  "proposals": [
    {
      "id": "629e492c-9056-46f5-8df4-24c80d6b5dac",
      "name": "Kisfeszültségű ajánlat",
      "voltage_level": "medium-high",
      "consumer_profile": "blank",
      "energy_fee": 34.22,
      "funds": true,
      "nogaranty": false,
      "garanty": true,
      "green": true,
      "loyalty": false,
      "online": true,
      "yearly": false,
      "co2": true,
      "start_date": "2020-09-22",
      "end_date": "2020-09-30",
      "isPublic": true
     }
  ]
}
```

comments: 
for the `deep insert` scenario, the id & fk should automatic be filled by framework, because in this case, generally, it means there are strong relationship between header and items, so that `deep insert` create the header - items in single db transaction and automatic fill related id & fk
also, if user fill the id property, it still should works.

**Comment by Soontao** [comment]
after version `0.2.39` meaningful error message has been added to `odata/server`

for  entity: 
```ts
@withEntitySetName('Classes')
@ODataModel()
export class Class {

  @IncKeyProperty()
  cid: number;

  @Property()
  name: string;

  @Property()
  desc: string

}

```

with payload:

```json
{
  "name": "string",
  "description": "string"
}
```

error message:
```json
{
  "error": {
    "code": 400,
    "message": "Entity 'Class': property 'description' is not defined (did you mean the property 'desc'), desc should not be null or undefined"
  }
}
```
